### ISSUE TITLE
Fix duplicated _tmpl.rs files

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#25]
The original C code contains a number of `_tmpl.c` files that get compiled once for each active bitdepth. This means that if both 8 and 16 bitdepths are enabled those files get compiled twice. To mimic this in the transpiled Rust, we have transpiled these files twice, e.g. `cdef_tmpl.c` gets transpiled to `cdef_tmpl_8.rs` and `cdef_tmpl_16.rs`.

We should see if we can merge the two Rust files back into a single one. Currently there's a lot of duplicated code between the two versions of a given file, with only relatively small differences between the two in some cases.

**Comment by kkysen** [comment]
The templated files are all for bitdepths, right?  And multiple bitdepths can be enabled at the same time, right?  If multiple can be active at once, then it makes deduplicating with features only a lot more complex.  It *may* be easier with macros or generics, though that may get complex as well.  I'd guess that generics would probably be the proper abstraction in the end once things are cleaned up, though I'm much less sure about right now.

The challenges in trying to use features for this, correct me if I'm wrong, we'd have to define e.x. `pixel_8` and `pixel_16` types, and then every item where such a bitdepth-differentiated item is used, duplicate that entire item to have a `*_8` and `*_16` version since we need to have both of them at the same time.  So if we do it this way, it'll still be complex and I'm not sure if we'll have actually deduplicated that much.

The challenges in trying to use macros for this is that all the code will be contained in a macro.  This way will probably be closest to the original C.

The challenges in trying to use generics for this is we can't use generics for `extern "C" fn`s, but I think we could:
* remove the `extern "C"` for functions that are not exported (I believe these are only those defined in `include/dav1d/` marked with `DAVID_API`, right?).
* for functions that are exported, define an 8- and 16-bitdepth `extern "C"` wrapper function that just calls the generic version.
Otherwise, it appears that the generic part of the bitdepths is neatly abstracted in `bitdepths.h` and they all seem amenable to conversion to Rust generics.

If we do go the generics route, I think it would be helpful to first deduplicate all the function declarations into `use`s and then make only the `DAVID_API` ones `pub extern "C"`.

**Comment by randomPoison** [comment]
I think you're right that we can't really do this with `#[cfg(feature)]` alone. I think generics are the right direction to go in, so doing a non-generic `extern "C"` function that just calls the generic function is the right way to go.

A good one to start with might be `cdef_tmpl`. I just did some work in that pair of files, and it seems like there are very few differences between the 8 and 16 bitdepth versions, so deduplication shouldn't be too hard hopefully.

**Comment by kkysen** [comment]
If it's done through generics, I think all the templated files will be done pretty much at once.  All the difference arise from `bitdepth.h` itself and it's pretty concise.  So once that's turned into generics, fixing the actual templated files should be much simpler.  I can start with `cdef_tmpl_*`, though, and thus start with fewer generic methods needed.  I'll see how it goes.
